(function(){
  'use strict';
  var fallback={provider:{nome:'Seu provedor',fone:'',celular:'',whatsapp:'',email:'',endereco:'',numero:'',bairro:'',cidade:'',estado:'',facebook:'',instagram:'',youtube:''},plans:[]};
  function all(s){return Array.prototype.slice.call(document.querySelectorAll(s));}
  function setText(s,v){if(v)all(s).forEach(function(e){e.textContent=v;});}
  function digits(v){return String(v||'').replace(/\D/g,'');}
  function clean(v){return String(v==null?'':v).replace(/<[^>]*>/g,'').trim();}
  function speed(v){var raw=clean(v),n=parseFloat(raw.replace(',','.'));if(!isFinite(n))return raw||'Consulte';if(n>=1000000)return Math.round(n/1000000);if(n>=1000)return Math.round(n/1000);return Math.round(n);}
  function money(v){var raw=clean(v),n=raw.indexOf(',')>=0?parseFloat(raw.replace(/\./g,'').replace(',','.')):parseFloat(raw);return isFinite(n)?n.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}):(raw||'Consulte');}
  function applyProvider(p){
    p=p||fallback.provider;var name=p.nome||p.razao||'Seu provedor';setText('[data-provider]',name);document.title=name+' | Internet fibra para todos os momentos';
    var address=[p.endereco,p.numero,p.bairro,p.cidade,p.estado].filter(Boolean).join(', ');setText('[data-address]',address||'Consulte nossa área de atendimento.');
    var phone=p.whatsapp||p.celular||p.fone||'',d=digits(phone);setText('[data-phone]',phone||'Atendimento');
    all('[data-whatsapp]').forEach(function(a){if(d.length>=10){a.href='https://wa.me/'+(d.indexOf('55')===0?d:'55'+d);a.target='_blank';a.rel='noopener';}else{a.hidden=true;}});
    all('[data-phone-link]').forEach(function(a){if(d.length>=10)a.href='tel:+'+(d.indexOf('55')===0?d:'55'+d);else a.removeAttribute('href');});
    setText('[data-email]',p.email||'Consulte o provedor');all('[data-email-link]').forEach(function(a){if(p.email)a.href='mailto:'+p.email;else a.removeAttribute('href');});
    var socials={Instagram:p.instagram,Facebook:p.facebook,YouTube:p.youtube},root=document.querySelector('[data-socials]');if(root){Object.keys(socials).forEach(function(label){var url=socials[label];if(!url)return;if(!/^https?:\/\//i.test(url))url='https://'+label.toLowerCase()+'.com/'+url.replace(/^@/,'');var a=document.createElement('a');a.href=url;a.textContent=label;a.target='_blank';a.rel='noopener';root.appendChild(a);});}
  }
  function renderPlans(plans){
    var root=document.getElementById('plan-grid');if(!root)return;plans=(plans||[]).filter(function(p){return String(p.oculto||'').toLowerCase()!=='sim';}).slice(0,3);
    if(!plans.length){root.innerHTML='<article class="loading"><strong>Consulte os planos disponíveis para seu endereço.</strong><br><br><a class="btn btn-primary" href="/cadastro.hhvm">Solicitar atendimento</a></article>';return;}
    root.textContent='';plans.forEach(function(p,i){var card=document.createElement('article'),description=clean(p.descricao)||'Internet fibra óptica com estabilidade para toda a sua rotina.';card.className='plan-card'+(i===1?' featured':'');card.innerHTML=(i===1?'<span class="plan-badge">Mais escolhido</span>':'')+'<div class="plan-top"><span class="plan-name"></span><div class="plan-speed"><b></b> <small>MEGA</small></div></div><div class="plan-body"><div class="plan-price"><small>R$</small><b></b><small>/mês</small></div><ul class="plan-features"><li>Internet fibra óptica</li><li>Conexão para todos os momentos</li><li class="dynamic-feature"></li></ul><a class="btn btn-primary" href="/cadastro.hhvm">Eu quero</a></div>';card.querySelector('.plan-name').textContent=p.nome||'Plano de internet';card.querySelector('.plan-speed b').textContent=speed(p.veldown||p.maxdown||p.nome);card.querySelector('.plan-price b').textContent=money(p.valor);card.querySelector('.dynamic-feature').textContent=description.slice(0,85);root.appendChild(card);});
  }
  function carousel(){var slides=all('[data-slide]'),dots=all('[data-dot]'),current=0,timer;if(!slides.length)return;function show(i){current=(i+slides.length)%slides.length;slides.forEach(function(s,n){s.classList.toggle('is-active',n===current);});dots.forEach(function(d,n){d.classList.toggle('is-active',n===current);});}function play(){if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;clearInterval(timer);timer=setInterval(function(){show(current+1);},6500);}var prev=document.querySelector('[data-prev]'),next=document.querySelector('[data-next]');if(prev)prev.addEventListener('click',function(){show(current-1);play();});if(next)next.addEventListener('click',function(){show(current+1);play();});dots.forEach(function(d){d.addEventListener('click',function(){show(parseInt(d.getAttribute('data-dot'),10)||0);play();});});document.querySelector('.carousel').addEventListener('mouseenter',function(){clearInterval(timer);});document.querySelector('.carousel').addEventListener('mouseleave',play);play();}
  var menu=document.querySelector('.menu-button'),nav=document.getElementById('nav');if(menu&&nav)menu.addEventListener('click',function(){var open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open?'true':'false');});carousel();setText('[data-year]',new Date().getFullYear());
  var request=new XMLHttpRequest();request.open('GET','/vpscloud-api/state.json?ts='+Date.now(),true);request.timeout=5000;request.onload=function(){try{if(request.status<200||request.status>=300)throw new Error('api');var data=JSON.parse(request.responseText);data=data&&data.ok?data:fallback;applyProvider(data.provider);renderPlans(data.plans);}catch(e){applyProvider(fallback.provider);renderPlans(fallback.plans);}};request.onerror=request.ontimeout=function(){applyProvider(fallback.provider);renderPlans(fallback.plans);};request.send();
})();
