(function(){'use strict';
var fallback={provider:{nome:'Seu provedor',fone:'',celular:'',whatsapp:'',email:'',endereco:'',numero:'',bairro:'',cidade:'',estado:'',site:'',facebook:'',instagram:'',youtube:'',tiktok:'',linkedin:''},plans:[]};
function all(s){return Array.prototype.slice.call(document.querySelectorAll(s))}function text(s,v){if(!v)return;all(s).forEach(function(e){e.textContent=v})}function digits(v){return String(v||'').replace(/\D/g,'')}function esc(v){return String(v==null?'':v)}
function speed(v){var raw=esc(v).trim(),n=parseFloat(raw.replace(',','.'));if(!isFinite(n))return raw||'Consulte';if(n>=1000000)return Math.round(n/1000000);if(n>=1000)return Math.round(n/1000);return Math.round(n)}
function money(v){var raw=esc(v).trim(),n;if(raw.indexOf(',')>=0)n=parseFloat(raw.replace(/\./g,'').replace(',','.'));else n=parseFloat(raw);if(!isFinite(n))return raw||'Consulte';return n.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}
function applyProvider(p){p=p||fallback.provider;var name=p.nome||p.razao||'Seu provedor';text('[data-provider]',name);document.title=name+' | Internet que acompanha você';var address=[p.endereco,p.numero,p.bairro,p.cidade,p.estado].filter(Boolean).join(', ');text('[data-address]',address||'Consulte nossa área de atendimento.');var phone=p.whatsapp||p.celular||p.fone||'';text('[data-phone]',phone||'Consulte o provedor');var d=digits(phone);all('[data-whatsapp]').forEach(function(a){if(d.length>=10){a.href='https://wa.me/'+d;a.target='_blank';a.rel='noopener'}else{a.hidden=true}});all('[data-phone-link]').forEach(function(a){if(d.length>=10)a.href='tel:+'+d;else a.removeAttribute('href')});text('[data-email]',p.email||'Consulte o provedor');all('[data-email-link]').forEach(function(a){if(p.email)a.href='mailto:'+p.email;else a.removeAttribute('href')});var socials={Instagram:p.instagram,Facebook:p.facebook,YouTube:p.youtube,TikTok:p.tiktok,LinkedIn:p.linkedin},root=document.querySelector('[data-socials]');if(root){Object.keys(socials).forEach(function(k){var u=socials[k];if(!u)return;if(!/^https?:\/\//i.test(u))u=(k==='Instagram'?'https://instagram.com/':'https://'+k.toLowerCase()+'.com/')+u.replace(/^@/,'');var a=document.createElement('a');a.href=u;a.textContent=k;a.target='_blank';a.rel='noopener';root.appendChild(a)})}}
function renderPlans(plans){var root=document.getElementById('plan-grid');if(!root)return;plans=(plans||[]).filter(function(p){return String(p.oculto||'').toLowerCase()!=='sim'}).slice(0,6);if(!plans.length){root.innerHTML='<article class="loading-card"><strong>Consulte os planos disponíveis para seu endereço.</strong><a class="button button-primary" href="/cadastro.hhvm">Solicitar atendimento</a></article>';return}root.textContent='';plans.forEach(function(p,i){var card=document.createElement('article');card.className='plan-card'+(i===1?' featured':'');var desc=p.descricao||'Internet para conectar sua rotina com estabilidade.';card.innerHTML=(i===1?'<span class="plan-badge">Mais procurado</span>':'')+'<span class="plan-name"></span><div class="plan-speed"><strong></strong><span>MEGA</span></div><p class="plan-description"></p><div class="plan-price"><small>A partir de R$</small><b></b><small>/mês</small></div><a class="button button-primary" href="/cadastro.hhvm">Quero este plano</a>';card.querySelector('.plan-name').textContent=p.nome||'Plano de internet';card.querySelector('.plan-speed strong').textContent=speed(p.veldown||p.maxdown||'');card.querySelector('.plan-description').textContent=desc.replace(/<[^>]*>/g,'').slice(0,150);card.querySelector('.plan-price b').textContent=money(p.valor);root.appendChild(card)})}
function init(data){data=data&&data.ok?data:fallback;applyProvider(data.provider);renderPlans(data.plans);text('[data-year]',new Date().getFullYear())}
var button=document.querySelector('.menu-button'),nav=document.getElementById('main-nav');if(button&&nav)button.addEventListener('click',function(){var open=nav.classList.toggle('open');button.setAttribute('aria-expanded',open?'true':'false')});
var request=new XMLHttpRequest();request.open('GET','/vpscloud-api/state.json?ts='+Date.now(),true);request.timeout=5000;request.onload=function(){try{if(request.status<200||request.status>=300)throw new Error('api');init(JSON.parse(request.responseText))}catch(e){init(fallback);document.documentElement.classList.add('api-fallback')}};request.onerror=request.ontimeout=function(){init(fallback);document.documentElement.classList.add('api-fallback')};request.send();
})();
