<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#071b3a">
  <title>Cadastro de plano</title>
  <style>
    *{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:radial-gradient(circle at 85% 10%,#ccefff,transparent 30%),#eef6fd;color:#10233f}.top{height:92px;background:#fff;display:flex;align-items:center;box-shadow:0 8px 30px #071b3a12}.wrap{width:min(1120px,calc(100% - 32px));margin:auto}.nav{display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:13px;font-weight:800}.brand img{width:78px;height:54px;object-fit:contain;border:1px solid #dbe7f2;border-radius:11px;padding:5px}.nav a{color:#10233f;text-decoration:none;font-weight:700}.main{padding:60px 0 90px}.head{text-align:center;margin-bottom:34px}.head span{font-size:11px;color:#087cf0;text-transform:uppercase;letter-spacing:.15em;font-weight:800}.head h1{font-size:clamp(34px,5vw,54px);margin:12px 0}.head p{color:#64748b}.grid{display:grid;grid-template-columns:.7fr 1.3fr;gap:22px;align-items:start}.summary,.form{border-radius:26px;padding:36px}.summary{position:sticky;top:24px;background:linear-gradient(150deg,#06182f,#0a2c51);color:#fff}.summary small{color:#6edfff;text-transform:uppercase;letter-spacing:.12em;font-weight:800}.summary h2{font-size:29px;overflow-wrap:anywhere}.summary p{color:#bfd2e6;line-height:1.7}.summary a{display:flex;justify-content:space-between;color:#fff;text-decoration:none;border:1px solid #ffffff2b;border-radius:12px;padding:15px;margin-top:15px}.form{background:#fff;border:1px solid #dae6f2;box-shadow:0 24px 65px #071b3a17}.form h2{margin-top:0}.form>p{color:#64748b}.fields{display:grid;grid-template-columns:1fr 1fr;gap:14px 12px;margin-top:24px}.form-section{grid-column:1/-1;background:#e8f4ff;color:#0a64b5;border-radius:10px;padding:11px 14px;margin-top:8px;font-size:12px;text-transform:uppercase;letter-spacing:.08em;font-weight:900}label{font-size:12px;font-weight:800}input,select,textarea{width:100%;margin-top:7px;border:1px solid #cfdeec;background:#f7fafd;border-radius:11px;padding:13px 14px;font:inherit;outline:none}input:focus,select:focus,textarea:focus{border-color:#168cf3;box-shadow:0 0 0 3px #168cf31b}.full{grid-column:1/-1}.btn{width:100%;border:0;border-radius:13px;padding:15px;margin-top:16px;background:linear-gradient(135deg,#087cf0,#14a9f5);color:#fff;font-weight:800;font-size:15px;cursor:pointer;box-shadow:0 14px 30px #087cf04d}.note{display:block;text-align:center;color:#718196;margin-top:12px;font-size:12px}
    @media(max-width:760px){.top{height:76px}.brand span{display:none}.main{padding:45px 0}.grid{grid-template-columns:1fr}.summary{position:static}.summary,.form{padding:26px}.fields{grid-template-columns:1fr}.full,.form-section{grid-column:auto}}
  .required-label{font-weight:400;color:#52657d}#cep-status{display:block;font-size:11px;font-weight:400;line-height:1.5;margin-top:7px;color:#52657d}</style>
<link rel="stylesheet" href="/midias_vpscloud/css/cadastro-options.css?v=20260910-1"></head>
<body>
  <header class="top"><div class="wrap nav"><a class="brand" href="/"><img src="/mkfiles/logo.jpg" alt="Logo"><span data-name>Provedor de Internet</span></a><a href="/central/">Central do Assinante</a></div></header>
  <main class="main"><div class="wrap">
    <div class="head"><span>Contratação</span><h1>Complete seu cadastro.</h1><p>Confirme o plano e preencha os dados para agilizar o atendimento.</p></div>
    <div class="grid">
      <aside class="summary"><small>Plano selecionado</small><h2 id="selected-plan">Carregando…</h2><p>Nossa equipe confirmará disponibilidade, cobertura e os detalhes da contratação.</p><button type="button" data-open-plan-picker aria-haspopup="dialog"><b>Trocar plano</b><span>→</span></button><a href="/central/"><b>Já sou cliente</b><span>→</span></a></aside>
      <form class="form" id="signup"><h2>Formulário de cadastro</h2><p>Preencha os campos identificados como (obrigatório).</p><div class="fields">
        <div class="form-section">Pagamento e plano</div>
        <label>Data de vencimento <span class="required-label">(obrigatório)</span><select name="venc" required><option value="">Escolha uma data</option><option>05</option><option>10</option><option>15</option><option>20</option><option>25</option></select></label>
        <label>Plano selecionado <span class="required-label">(obrigatório)</span><input name="plano" id="plan-input" readonly><button type="button" data-open-plan-picker class="change-plan-inline" aria-haspopup="dialog">Escolher outro plano</button></label>
        <div class="form-section">Dados de acesso</div>
        <label>Login <span class="required-label">(obrigatório)</span><input name="login" required placeholder="Crie um login"></label><label>Senha <span class="required-label">(obrigatório)</span><input name="senha" type="password" required placeholder="Crie uma senha"></label>
        <div class="form-section">Informações do titular</div>
        <label>Nome completo <span class="required-label">(obrigatório)</span><input name="nome" required placeholder="Seu nome"></label><label>E-mail <span class="required-label">(obrigatório)</span><input name="email" type="email" required></label>
        <label>CPF / CNPJ <span class="required-label">(obrigatório)</span><input name="documento" required inputmode="numeric" placeholder="Somente números"></label><label>RG<input name="rg" placeholder="Documento de identidade"></label>
        <label>Data de nascimento<input name="nascimento" inputmode="numeric" maxlength="10" placeholder="DD/MM/AAAA"></label><label>Telefone fixo<input name="fone" inputmode="tel" placeholder="(00) 0000-0000"></label>
        <label>Telefone celular / WhatsApp <span class="required-label">(obrigatório)</span><input name="telefone" required inputmode="tel" placeholder="(00) 9 0000-0000"></label><label>Código promocional<input name="promocional" placeholder="Se tiver recebido um"></label>
        <div class="form-section">Endereço</div>
        <label>CEP <span class="required-label">(obrigatório)</span><input name="cep" required inputmode="numeric" autocomplete="postal-code" maxlength="9" pattern="[0-9]{5}-?[0-9]{3}" aria-describedby="cep-status" placeholder="00000-000"><small id="cep-status" role="status" aria-live="polite">Digite o CEP para buscar o endereço.</small></label><label>Logradouro <span class="required-label">(obrigatório)</span><input name="endereco" required placeholder="Rua, avenida, travessa..."></label>
        <label>Número <span class="required-label">(obrigatório)</span><input name="numero" required placeholder="Número"></label><label>Complemento<input name="complemento" placeholder="Apto., bloco, casa..."></label>
        <label>Bairro <span class="required-label">(obrigatório)</span><input name="bairro" required placeholder="Seu bairro"></label><label>Cidade <span class="required-label">(obrigatório)</span><input name="cidade" required placeholder="Sua cidade"></label>
        <label>Estado <span class="required-label">(obrigatório)</span><select name="estado" required><option value="">UF</option><option>AC</option><option>AL</option><option>AP</option><option>AM</option><option>BA</option><option>CE</option><option>DF</option><option>ES</option><option>GO</option><option>MA</option><option>MT</option><option>MS</option><option>MG</option><option>PA</option><option>PB</option><option>PR</option><option>PE</option><option>PI</option><option>RJ</option><option>RN</option><option>RS</option><option>RO</option><option>RR</option><option>SC</option><option>SP</option><option>SE</option><option>TO</option></select></label><label>Referência<input name="referencia" placeholder="Ponto de referência"></label>
        <label class="full">Observações<textarea name="mensagem" rows="4" placeholder="Informe detalhes ou o melhor horário para contato"></textarea></label>
        <label class="hide-field" aria-hidden="true">Não preencher<input name="website" tabindex="-1" autocomplete="off"></label>
      </div><button class="btn" id="submit-button" type="submit">Enviar cadastro pelo WhatsApp</button><small class="note" id="submit-note">A senha não será incluída na mensagem enviada.</small><div id="form-result" role="status" style="display:none;margin-top:16px;padding:14px;border-radius:11px;text-align:center"></div></form>
    </div>
  </div></main>
  <script>
    let number='';const params=new URLSearchParams(location.search),plan=params.get('plano')||'Plano sob consulta',systemMode=location.pathname.indexOf('cadastro-sistema')!==-1;document.querySelector('#selected-plan').textContent=plan;document.querySelector('#plan-input').value=plan;document.querySelector('.hide-field').style.display='none';if(systemMode){document.querySelector('#submit-button').textContent='Enviar solicitação ao provedor';document.querySelector('#submit-note').textContent='Seu cadastro será registrado no sistema do provedor para análise.'}
    fetch('/abgs-data.php?v=4').then(r=>r.json()).then(d=>{const e=d.empresa||{};document.querySelectorAll('[data-name]').forEach(x=>x.textContent=e.nome||'Provedor de Internet');number=(e.whatsapp||e.celular||e.fone||'').replace(/\D/g,'').replace(/^55/,'');document.title='Cadastro | '+(e.nome||'Provedor')});
    document.querySelector('#signup').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),button=document.querySelector('#submit-button'),result=document.querySelector('#form-result');if(systemMode){button.disabled=true;button.textContent='Enviando…';result.style.display='none';try{const response=await fetch('/abgs-signup.php',{method:'POST',body:f,credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest'}}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'Não foi possível enviar o cadastro.');result.style.display='block';result.style.background='#e8fff2';result.style.color='#08733c';result.textContent=`Solicitação nº ${data.id} registrada com sucesso. A equipe entrará em contato.`;form.querySelectorAll('input:not([readonly]),textarea').forEach(x=>x.value='');button.textContent='Cadastro enviado'}catch(error){result.style.display='block';result.style.background='#fff0f0';result.style.color='#a51d2d';result.textContent=error.message;button.disabled=false;button.textContent='Tentar novamente'}return}const line=(label,key)=>f.get(key)?`${label}: ${f.get(key)}`:'',parts=[`Olá! Quero realizar meu cadastro no plano ${f.get('plano')}.`,line('Vencimento','venc'),line('Login','login'),line('Nome','nome'),line('E-mail','email'),line('CPF/CNPJ','documento'),line('RG','rg'),line('Nascimento','nascimento'),line('Telefone fixo','fone'),line('Celular/WhatsApp','telefone'),line('Código promocional','promocional'),line('CEP','cep'),line('Endereço','endereco'),line('Número','numero'),line('Complemento','complemento'),line('Bairro','bairro'),line('Cidade','cidade'),line('Estado','estado'),line('Referência','referencia'),line('Observações','mensagem')].filter(Boolean);if(number)location.href='https://wa.me/55'+number+'?text='+encodeURIComponent(parts.join('\n'));else alert('Canal de atendimento indisponível. Entre em contato com o provedor.')});
  </script>
<script src="/midias_vpscloud/js/cadastro-cep.js?v=20260910-1"></script><dialog id="plan-picker" class="plan-picker" aria-labelledby="picker-title" aria-describedby="picker-description"><div class="picker-header"><div><h2 id="picker-title">Escolha seu plano</h2><p id="picker-description">Deslize para comparar. Seus dados preenchidos serão mantidos.</p></div><button type="button" id="picker-close" class="picker-close" aria-label="Fechar seleção de plano">×</button></div><p id="picker-status" role="status" aria-live="polite"></p><button type="button" id="picker-retry" hidden>Tentar novamente</button><div id="picker-rail" class="picker-rail" role="region" aria-label="Escolha entre os planos disponíveis" tabindex="0"></div><div class="picker-footer"><button type="button" id="picker-previous" aria-label="Plano anterior" aria-controls="picker-rail">‹</button><span id="picker-range" role="status" aria-live="polite"></span><button type="button" id="picker-next" aria-label="Próximo plano" aria-controls="picker-rail">›</button></div></dialog><script src="/midias_vpscloud/js/cadastro-options.js?v=20260910-1"></script></body></html>
